// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBlNADbgcp9EOcnG79HlE_zDayj3JSILk0',
//     appId: '1:182129681793:web:77627a74571a0f74a33480',
//     messagingSenderId: '182129681793',
//     projectId: 'pfm-flutter',
//     authDomain: 'pfm-flutter.firebaseapp.com',
//     storageBucket: 'pfm-flutter.appspot.com',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAyO_7mZ4huoTYjPCtGCzk7Gi_Jvmes8uI',
//     appId: '1:182129681793:android:040f0f0759670d0ea33480',
//     messagingSenderId: '182129681793',
//     projectId: 'pfm-flutter',
//     storageBucket: 'pfm-flutter.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDnaG_4zcMV2Gi8JMqzGBuFpTKoSPHCHCM',
//     appId: '1:182129681793:ios:fb0b22ef51ae3e3da33480',
//     messagingSenderId: '182129681793',
//     projectId: 'pfm-flutter',
//     storageBucket: 'pfm-flutter.appspot.com',
//     iosBundleId: 'com.example.financeTracker',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDnaG_4zcMV2Gi8JMqzGBuFpTKoSPHCHCM',
//     appId: '1:182129681793:ios:fb0b22ef51ae3e3da33480',
//     messagingSenderId: '182129681793',
//     projectId: 'pfm-flutter',
//     storageBucket: 'pfm-flutter.appspot.com',
//     iosBundleId: 'com.example.financeTracker',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBlNADbgcp9EOcnG79HlE_zDayj3JSILk0',
//     appId: '1:182129681793:web:4886ddde856652fda33480',
//     messagingSenderId: '182129681793',
//     projectId: 'pfm-flutter',
//     authDomain: 'pfm-flutter.firebaseapp.com',
//     storageBucket: 'pfm-flutter.appspot.com',
//   );
// }
